# Generated by Django 3.1.2 on 2022-06-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='phone',
            name='release_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
